### ISSUE TITLE
-bash: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by dleung18** [pviotti/issuu-pdf-dl#7]
I issued the comand 
ruby ./issuu-pdf-dl.rb <https://issuu.com/doushuroll/book2_2022>
in the terminal and I got the following error:
-bash: syntax error near unexpected token `newline'
please help.

**Comment by pviotti** [comment]
sorry for the delay. It seems to be working here. Though that URL does not exist, and it's not in the right format: it should be like `https://issuu.com/<username>/docs/<name of the book>`. Not sure what's the error you got, probably some issue with the parameters from command line - please check command line arguments and version of the Ruby interpreter (`ruby --version`).

**Comment by pviotti** [comment]
Closing this issue, as the tool has been rewritten in Python. Please try again and reopen the issue if needed. Thanks
